apiVersion: tekton.dev/v1beta1
kind: Pipeline

metadata:
  name: app-pipeline

spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws

  params:
    - name: repo-url
      type: string

    - name: branch
      type: string

    - name: app-name
      type: string

    - name: build-image
      type: string

  tasks:

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask

      workspaces:
        - name: output
          workspace: pipeline-workspace

      params:
        - name: url
          value: $(params.repo-url)

        - name: revision
          value: $(params.branch)

    - name: npminstall
      taskRef:
        name: npm

      runAfter:
        - clone

      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: jasmine

      runAfter:
        - npminstall

      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask

      runAfter:
        - tests

      workspaces:
        - name: source
          workspace: pipeline-workspace

        - name: dockerconfig
          workspace: dockerconfig-ws

      params:
        - name: IMAGE
          value: "us.icr.io/$(params.build-image)"

        - name: TLSVERIFY
          value: "false"
