apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: npm

spec:
  workspaces:
    - name: source

  steps:
    - name: npminstall
      image: node:18

      workingDir: /workspace/source

      script: |
        #!/bin/sh
        npm install
